export const mockOptions = [
  'AJAX',
  'Bootstrap',
  'CSS Display + Positioning',
  'Database OO Design Patterns',
  'DDL & Schema Design',
  'Deployment with Heroku',
  'Git Intro',
  'Git Workflow',
  'Hashing and JWTs with Node',
  'How the Web Works',
  'Intermediate JS 1',
  'Intermediate JS 2',
  'Intro to Express.js',
  'Intro to Node.js',
  'Intro to Postgres with Node',
  'Introduction to Big-O',
  'Introduction to Databases',
  'Introduction to Python',
  'Pair Programming',
  'Professional Coding',
  'Python Data Structures',
  'Python Object Orientation',
  'Python Tools & Techniques',
  'React Component Lifecycle',
  'React Context',
  'React Events',
  'React Forms',
  'React State',
  'ReactJS',
  'Relationships in SQL',
  'SQL Alchemy',
  'SQL Querying',
  'Validation with JSONSchema',
  'Whiteboarding',
  'Working With APIs',
];

export const mockResults = [
  {
    matches: [
      'React Redux, React-Redux',
      'The React Dev Tools are a great way to debug your react-redux applications',
      'Combine a Redux store with a React app, We\'ll use a library called react-redux',
    ],
    title: 'React Redux',
    url: 'http://curric.rithmschool.com/r13/lectures/react-redux-intro/',
  },
  {
    matches: [
      'ReactJS, React',
      'A component is a React class with a render method, we add our component to HTML with ReactDOM.render',
      'Styling React, React',
    ],
    title: 'ReactJS',
    url: 'http://curric.rithmschool.com/r13/lectures/react-intro/',
  },
  {
    matches: [
      'React-Redux Part 2, React Router and Redux',
      'The React-Redux docs have a section discussing the difference between mapDispatchToProps and this.props.dispatch, and when you may want to prefer the former',
      'Include React-Router with Redux, React controls UI state',
    ],
    title: 'React-Redux Part 2',
    url: 'http://curric.rithmschool.com/r13/lectures/react-redux-disp-props/',
  },
  {
    matches: [
      'React Wrapup, React',
      'Create React App includes Webpack',
      'Refer to React-created element, what does this mean for my React knowledge?',
    ],
    title: 'React Wrapup',
    url: 'http://curric.rithmschool.com/r13/lectures/react-wrapup/',
  },
  {
    matches: [
      'React State, React State',
      'In React, state is always an object, React can have event handlers!',
      'define react state, React is, on click',
    ],
    title: 'React State',
    url: 'http://curric.rithmschool.com/r13/lectures/react-state/',
  },
  {
    matches: [
      'React Events, React Events',
      'Is slightly different in React, any event you can listen for in JS, you can listen for in React',
      'Attach event handlers to components in React, AJAX with React',
    ],
    title: 'React Events',
    url: 'http://curric.rithmschool.com/r13/lectures/react-events/',
  },
  {
    matches: [
      'React Lifecycle - Updating',
      'This is only useful if you are using the React Context API - if so, you may want to learn about and use this argument in any shouldComponentUpdate call',
      'React often can recognize last ToDo is only new one, React compares node identity with key',
    ],
    title: 'React Lifecycle - Updating',
    url: 'http://curric.rithmschool.com/r13/lectures/react-lifecycle-updating/',
  },
  {
    matches: [
      'React: CRA, Modules, & Testing, Create React App',
      'You can get react.js and react-dom.js from a CDN, Create-React-App is a utility script that',
      'Understand what Create React App is and how to use, creates a skeleton react project',
    ],
    title: 'React: CRA, Modules, & Testing',
    url: 'http://curric.rithmschool.com/r13/lectures/react-cra/',
  },
  {
    matches: [
      'Client-Side Routing with React Router, React Router',
      'to get started wth React Router, install react-router-dom',
      'Implement basic client-side routing with React Router',
    ],
    title: 'Client-Side Routing with React Router',
    url: 'http://curric.rithmschool.com/r13/lectures/react-router-intro/',
  },
  {
    matches: [
      'React Forms, Introduction to React Form Components',
      'In React we generally have downward data flow. "Smart" parent components with simpler child components',
      'Build forms with React',
    ],
    title: 'React Forms',
    url: 'http://curric.rithmschool.com/r13/lectures/react-forms/',
  },
];
